In [4]:
import torch
a=torch.tensor([4,9],dtype=torch.float32)
print(a.mean())


tensor(6.5000)


In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

# 自定义数据集
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return len(self.data)

# 创建数据集
data = [1, 2, 3, 4, 5]
dataset = MyDataset(data)

# 创建数据加载器
batch_size = 2
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# 迭代获取批次样本
for batch in dataloader:
    print(batch)

tensor([1, 2])
tensor([5, 4])
tensor([3])
