In [4]:
import torch
a=torch.tensor([4,9],dtype=torch.float32)
print(a.mean())


tensor(6.5000)


In [1]:
# 定义一个输入对象  
input_obj = {'a': 1, 'b': 2}  
  
# 定义一组patch  
patches = [  
    {'a': lambda x: x + 1},  
    {'b': lambda x: x * 2}  
]  
  
# 应用patch  
patched_obj = patches[1].patches(input_obj, patches)  
  
# 输出结果  
print(patched_obj)  # 输出: {'a': 2, 'b': 4}
print(patches[1].patches)

AttributeError: 'dict' object has no attribute 'patches'

In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

# 自定义数据集
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return len(self.data)

# 创建数据集
data = [1, 2, 3, 4, 5]
dataset = MyDataset(data)

# 创建数据加载器
batch_size = 2
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# 迭代获取批次样本
for batch in dataloader:
    print(batch)

tensor([1, 2])
tensor([5, 4])
tensor([3])
